/**
 * Report Generation Script
 * 
 * This script generates a beautiful HTML report from Cucumber JSON output
 * Run after tests complete: npm run report
 * 
 * Why generate reports?
 * - Visual representation of test results
 * - Easy to share with stakeholders
 * - Historical tracking of test runs
 * - Screenshots attached to failed scenarios
 */

// Import the report generator library
const report = require('multiple-cucumber-html-reporter');
const os = require('os');

// Load environment variables from .env file into process.env
require('dotenv').config();

// OS and Node info
const platformName = os.type(); // 'Linux', 'Darwin', 'Windows_NT'
const platformVersion = os.release();
const deviceName = os.hostname();
const browserName = process.env.BROWSER || 'chromium';

const nodeVersion = process.version;

/**
 * Generate HTML Report
 * 
 * Reads cucumber-report.json and creates HTML report with:
 * - Test summary (passed/failed counts)
 * - Feature breakdown
 * - Scenario details
 * - Screenshots for failures
 * - Execution time
 * - Browser/platform info
 */
report.generate({
  // Where to find JSON reports (generated by Cucumber)
  jsonDir: 'test-reports/',

  // Where to save HTML report
  reportPath: 'test-reports/html-report/',

  // Metadata: Information about test environment
  metadata: {
    browser: {
      name: browserName,
      version: process.env.RUN_BROWSER_VERSION || 'latest'  // Retrieved from env set in BrowserManager
    },
    device: deviceName,
    platform: {
      name: platformName,    // OS: win32, darwin (Mac), linux
      version: platformVersion    // Node.js version
    }
  },

  // Custom data to display in report header
  customData: {
    title: 'Test Execution Report',
    data: [
      { label: 'Project', value: 'Playwright Cucumber Framework' },
      { label: 'Release', value: '1.0.0' },
      { label: 'Execution Start Time', value: process.env.TEST_STARTED_TIME || new Date().toLocaleString() },
      { label: 'Execution Completed Time', value: process.env.TEST_COMPLETED_TIME || new Date().toLocaleString() }
    ]
  }
});

console.log('═══════════════════════════════════════════════════');
console.log('✅ HTML Report generated successfully!');
console.log('📂 Location: reports/html-report/index.html');
console.log('═══════════════════════════════════════════════════');
// Report will be in: reports/html-report/index.html
